language: ruby

rvm:
  - 2.2

before_script:
  - gem install awesome_bot

script:
  - awesome_bot README.md --allow-redirect --allow-ssl --white-list https://academy.yandex.ru/events/testing/spb-2014/,https://vimeo.com/88662183,https://vimeo.com/88676857,https://vimeo.com/89234167,https://vimeo.com/89974203,https://vimeo.com/90074270,http://www.ias.ac.in/article/fulltext/sadh/034/01/0003-0025,https://t.me/sqaunderhood,http://creativecommons.org/publicdomain/zero/1.0/

notifications:
  email:
    recipients:
      - estetus+travis-ci@gmail.com
    on_success: change
    on_failure: always
